- name: "update packages"
  become: true
  apt:
      update_cache: yes
      autoremove: yes

- name: "install apache"
  become: true
  apt:
#      update_cache: yes
      name: [apache2]
      state: latest

#- name: "create file"
#  become: true
#  file:
#      path: /var/www/html/index.html
#      state: touch

#- copy: "push files"
#  become: true
#  copy:
#      src: index.html
#      dest: /var/www/html/index.html
